### ISSUE TITLE
Search by logical id or identifier doesn't return the same results.

### ISSUE THREAD

**Issue by nriss** [arkhn/warehouse-api#136]
Searching by logical id (in dev) returns more Observation resources, that are not linked to the current performer with this logical id

Observation?performer=3838c173-34b7-4d38-93f8-557db5abefb8 (logical id)
Observation?performer:identifier=17582 (identifier)

**Comment by simonvadee** [comment]
this should have been fixed: see arkhn/pyfhirstore#59

we need to redeploy on dev maybe

**Comment by nriss** [comment]
The error is still present

Example on staging :
Observation?encounter=42715dc9-b141-4ab1-8075-2fb43b5e56de (11 results with different encounter ids)
Observation?encounter:identifier=167312 (4 results as expected)

**Comment by elsiehoffet-94** [comment]
I don't think you can search by logical id on a reference, but rather with `<ResourceType>/logicalId`.

For example this
`Observation?encounter=Encounter/42715dc9-b141-4ab1-8075-2fb43b5e56de`
 instead of 
 `Observation?encounter=42715dc9-b141-4ab1-8075-2fb43b5e56de`

**Comment by nriss** [comment]
It looks working with that example:
https://staging.arkhn.com/api/Observation?encounter=0fc0dc5c-465b-4a42-9d38-032b5f62d532
https://staging.arkhn.com/api/Observation?encounter:identifier=135870

I will try few more examples
